apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    appName: backend
    projectName: expense
spec:
  volumes:
    - name: vault
      emptyDir:
        sizeLimit: 5Mi
  initContainers:
    - name: vault
      image: 368761340104.dkr.ecr.us-east-1.amazonaws.com/vault-init-container:v2
      imagePullPolicy: Always
      env:
        - name: VAULT_ADDR
          value: "https://vault-internal.ramdevops78.online:8200"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key: token
        - name: SECRET_NAME
          value: expense-dev/backend
        - name: VAULT_SKIP_VERIFY
          value: "TRUE"
      volumeMounts:
        - name: vault
          mountPath: /data
    - name: schema
      image: 368761340104.dkr.ecr.us-east-1.amazonaws.com/schema-init-container:v2
      imagePullPolicy: Always
      volumeMounts:
        - name: vault
          mountPath: /data
  containers:
    - name: backend
      image: 368761340104.dkr.ecr.us-east-1.amazonaws.com/expense-backend:2.0.1
      imagePullPolicy: Always
      command: ["sleep","1000"]
      volumeMounts:
        - name: vault
          mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    appName: backend
    projectName: expense
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---